CREATE TABLE board(
num INT UNSIGNED NOT NULL,
subnum INT UNSIGNED NOT NULL,
PRIMARY KEY(num,subnum))
ENGINE=INNODB DEFAULT CHARSET=UTF8;
--복합키 지정
ALTER TABLE board DROP PRIMARY KEY;
--복합키 삭제
ALTER TABLE board ADD PRIMARY KEY(num,subnum);
--복합키 지정
INSERT INTO board VALUES (1,1);
INSERT INTO board VALUES (1,2);
INSERT INTO board VALUES (2,1);
INSERT INTO board VALUES (2,2);
--중복 안 됨
